# - Look for GNU flex, the lexer generator.
# Defines the following:
#  FLEX_EXECUTABLE - path to the flex executable
#  FLEX_FILE - parse a file with flex
#  FLEX_PREFIX_OUTPUTS - Set to true to make FLEX_FILE produce outputs of
#                        lex.${filename}.c, not lex.yy.c . Passes -P to flex. 

IF(NOT DEFINED FLEX_PREFIX_OUTPUTS)
  SET(FLEX_PREFIX_OUTPUTS TRUE)
ENDIF(NOT DEFINED FLEX_PREFIX_OUTPUTS) 

IF(NOT FLEX_EXECUTABLE)
  MESSAGE(STATUS "Looking for flex")
  FIND_PROGRAM(FLEX_EXECUTABLE flex)
  IF(FLEX_EXECUTABLE)
    MESSAGE(STATUS "Looking for flex -- ${FLEX_EXECUTABLE}")
  ENDIF(FLEX_EXECUTABLE)
ENDIF(NOT FLEX_EXECUTABLE) 

IF(FLEX_EXECUTABLE)
	MACRO(FLEX_FILE FILENAME)
	GET_FILENAME_COMPONENT(PATH "${FILENAME}" PATH)
    IF("${PATH}" STREQUAL "")
      SET(PATH_OPT "")
    ELSE("${PATH}" STREQUAL "")
      SET(PATH_OPT "/${PATH}")
    ENDIF("${PATH}" STREQUAL "")
	IF(NOT EXISTS "${CMAKE_CURRENT_BINARY_DIR}${PATH_OPT}")
      FILE(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}${PATH_OPT}")
    ENDIF(NOT EXISTS "${CMAKE_CURRENT_BINARY_DIR}${PATH_OPT}")
    GET_FILENAME_COMPONENT(PREFIX "${FILENAME}" NAME_WE)
    GET_FILENAME_COMPONENT(EXTENSION "${FILENAME}" EXT)
    ADD_CUSTOM_COMMAND(
    	OUTPUT "lex.${PREFIX}.c" "lex.${PREFIX}.h"
    	COMMAND "${FLEX_EXECUTABLE}"
    	ARGS "--header-file=lex.${PREFIX}.h"
    	"--stdout"
    	"-t"
    	"${PREFIX}${EXTENSION}"
    	">" 
    	"lex.${PREFIX}.c"
    )
    SET_SOURCE_FILES_PROPERTIES("lex.${PREFIX}.c" PROPERTIES LANGUAGE CXX GENERATED TRUE)
	ENDMACRO(FLEX_FILE)
ENDIF(FLEX_EXECUTABLE)
