/* Generated by gliss-attr (111/06/30 15:38:25) copyright (c) 2009 IRIT - UPS */

#include <arm/api.h>
#include <arm/id.h>
#include <arm/macros.h>
#include <arm/grt.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef unsigned long otawa_kind_t;
typedef otawa_kind_t (*fun_t)(arm_inst_t *inst);

/*** function definition ***/

static otawa_kind_t otawa_kind_UNKNOWN(arm_inst_t *inst) {
	return 0;
}

static otawa_kind_t otawa_kind_MOV_RD__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MOV_RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_TST_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUB_RD__RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUB_SP___ID__2A_4(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUB_RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUB_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRH_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRH_RD___LT_RD___ID__2A_2_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRB_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRB_RD___LT_RD___ID_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STR_RD___LT_SP___ID__2A_4_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STR_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STR_RD___LT_RD___ID__2A_4_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STMIA_RD_21___LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SBC_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ROR_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_PUSH__LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_PUSH__LB_S_RB__0(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_POP__LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_POP__LB_S_RB__0(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ORR_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_NEG_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MVN_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MUL_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LSR_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LSR_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LSL_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LSL_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRSH_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRSB_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRH_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRH_RD___LT_RD___ID__2A_2_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRB_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRB_RD___LT_RD___ID_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDR_RD___LT_SP___ID__2A_4_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDR_RD___LT_PC___ID__2A_4_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDR_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDR_RD___LT_RD___ID__2A_4_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDMIA_RD_21___LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_EOR_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CMP_RD__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CMP_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CMP_RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CMN_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_BX_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_BLX_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_BLS_D(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_BIC_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_S__ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ASR_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ASR_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_AND_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADD_RD__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADD_RD__RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADD_SP___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADD_RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADD_RD___ID_0(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADD_RD___ID_1(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADD_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADC_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MRSS_S__CPSR(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MRSS_S__SPSR(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR___S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_FSXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_SXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_FXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_FSX__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_XC__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_SC__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_SX__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_F__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_FX__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_FS__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_C__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_X__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_F__S_0(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR___S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_FSXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_SXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_FXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_FSX__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_XC__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_SC__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_SX__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_F__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_FX__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_FS__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_C__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_X__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_F__S_0(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR____ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_FSXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_SXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_FXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_FSX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_XC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_SC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_SX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_F___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_FX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_FS___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_C___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_X___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_CPSR_F___ID_0(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR____ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_FSXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_SXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_FXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_FSX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_XC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_SC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_SX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_F___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_FX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_FS___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_C___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_X___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MSRS_SPSR_F___ID_0(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CLZS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SWPS_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SWPSB_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UMLALSS_S_S_S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SMLALSS_S_S_S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_UMULLSS_S_S_S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SMULLSS_S_S_S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MULSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MLASS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SWIS_D(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SMSS_SS___LB_S_RB_S(arm_inst_t *inst) {
	uint32_t __gtmp_2;
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((uint32_t)(ARM_SMSS_SS___LB_S_RB_S_x_cond_cond)) == 14))
		__gtmp_0 = 0;
	else
		__gtmp_0 = 1;
	if(ARM_SMSS_SS___LB_S_RB_S_x_setl)
		__gtmp_1 = 32;
	else
		__gtmp_1 = 64;
	if(((ARM_SMSS_SS___LB_S_RB_S_x_setl && (((uint32_t)(ARM_SMSS_SS___LB_S_RB_S_x_rn_r)) == 13)) && (((uint32_t)(ARM_SMSS_SS___LB_S_RB_S_x_reglist_r)) & (1 << 15))))
		__gtmp_2 = (2 | 8);
	else
		__gtmp_2 = 0;
	return ((((16 | 32768L) | __gtmp_0) | __gtmp_1) | __gtmp_2);

};

static otawa_kind_t otawa_kind_LDRSSH_S___LT_SS_SSSS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRSSH_S___LT_SS_S_IDSS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRSSB_S___LT_SS_SSSS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRSSB_S___LT_SS_S_IDSS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRSH_S___LT_SS_SSSS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_LDRSH_S___LT_SS_S_IDSS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRSH_S___LT_SS_SSSS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_STRSH_S___LT_SS_S_IDSS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SRSSS_S___LT_SS__SS__S__IDSS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SRSSS_S___LT_SS_S_IDSS(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_BSS_X(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if(ARM_BSS_X_x_setl)
		__gtmp_0 = 4;
	else
		__gtmp_0 = 0;
	if((((uint32_t)(ARM_BSS_X_x_cond_cond)) == 14))
		__gtmp_1 = 0;
	else
		__gtmp_1 = 1;
	return ((2 | __gtmp_0) | __gtmp_1);

};

static otawa_kind_t otawa_kind_BXS_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_TSTS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_TSTS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_TSTS_S__S__S__ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_TEQS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_TEQS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_TEQS_S__S__S__ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SUBSS_S__S__S__S__ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SBCSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SBCSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_SBCSS_S__S__S__S__ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_RSCSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_RSCSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_RSCSS_S__S__S__S__ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_RSBSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_RSBSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_RSBSS_S__S__S__S__ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ORRSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ORRSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ORRSS_S__S__S__S__ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MVNSS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MVNSS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MVNSS_S__S__S__ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MOVSS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_MOVSS_S__S__S_S(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((((uint32_t)(ARM_MOVSS_S__S__S_S_x_cond_cond)) == 14) && (ARM_MOVSS_S__S__S_S_x_shifter_operand_r_r == 15)) && 0))
		__gtmp_0 = (8 | 2);
	else
		__gtmp_0 = 0;
	if((((uint32_t)(ARM_MOVSS_S__S__S_S_x_cond_cond)) == 14))
		__gtmp_1 = 0;
	else
		__gtmp_1 = 1;
	return (__gtmp_0 | __gtmp_1);

};

static otawa_kind_t otawa_kind_MOVSS_S__S__S__ID(arm_inst_t *inst) {
	uint32_t __gtmp_1;
	uint32_t __gtmp_0;
	if((((((uint32_t)(ARM_MOVSS_S__S__S__ID_x_cond_cond)) == 14) && (ARM_MOVSS_S__S__S__ID_x_shifter_operand_r_r == 15)) && ((((uint32_t)(ARM_MOVSS_S__S__S__ID_x_shifter_operand_shiftAmt)) == 0) && (((uint32_t)(ARM_MOVSS_S__S__S__ID_x_shifter_operand_shiftKind)) != 3))))
		__gtmp_0 = (8 | 2);
	else
		__gtmp_0 = 0;
	if((((uint32_t)(ARM_MOVSS_S__S__S__ID_x_cond_cond)) == 14))
		__gtmp_1 = 0;
	else
		__gtmp_1 = 1;
	return (__gtmp_0 | __gtmp_1);

};

static otawa_kind_t otawa_kind_EORSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_EORSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_EORSS_S__S__S__S__ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CMPS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CMPS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CMPS_S__S__S__ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CMNS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CMNS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_CMNS_S__S__S__ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_BICSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_BICSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_BICSS_S__S__S__S__ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ANDSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ANDSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ANDSS_S__S__S__S__ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDSS_S__S__S__S__ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADCSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADCSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADCSS_S__S__S__S__ID(arm_inst_t *inst) {
return 0;
};

static otawa_kind_t otawa_kind_ADDSS_S__S___ID(arm_inst_t *inst) {
return 0;
};




/*** function table ***/
static fun_t kind_funs[] = {
	otawa_kind_UNKNOWN,
	otawa_kind_MOV_RD__S,
	otawa_kind_MOV_RD___ID,
	otawa_kind_TST_RD__RD,
	otawa_kind_SUB_RD__RD__RD,
	otawa_kind_SUB_SP___ID__2A_4,
	otawa_kind_SUB_RD___ID,
	otawa_kind_SUB_RD__RD___ID,
	otawa_kind_STRH_RD___LT_RD__RD__RT_,
	otawa_kind_STRH_RD___LT_RD___ID__2A_2_RT_,
	otawa_kind_STRB_RD___LT_RD__RD__RT_,
	otawa_kind_STRB_RD___LT_RD___ID_RT_,
	otawa_kind_STR_RD___LT_SP___ID__2A_4_RT_,
	otawa_kind_STR_RD___LT_RD__RD__RT_,
	otawa_kind_STR_RD___LT_RD___ID__2A_4_RT_,
	otawa_kind_STMIA_RD_21___LB_S_RB_,
	otawa_kind_SBC_RD__RD,
	otawa_kind_ROR_RD__RD,
	otawa_kind_PUSH__LB_S_RB_,
	otawa_kind_PUSH__LB_S_RB__0,
	otawa_kind_POP__LB_S_RB_,
	otawa_kind_POP__LB_S_RB__0,
	otawa_kind_ORR_RD__RD,
	otawa_kind_NEG_RD__RD,
	otawa_kind_MVN_RD__RD,
	otawa_kind_MUL_RD__RD,
	otawa_kind_LSR_RD__RD,
	otawa_kind_LSR_RD__RD___ID,
	otawa_kind_LSL_RD__RD,
	otawa_kind_LSL_RD__RD___ID,
	otawa_kind_LDRSH_RD___LT_RD__RD__RT_,
	otawa_kind_LDRSB_RD___LT_RD__RD__RT_,
	otawa_kind_LDRH_RD___LT_RD__RD__RT_,
	otawa_kind_LDRH_RD___LT_RD___ID__2A_2_RT_,
	otawa_kind_LDRB_RD___LT_RD__RD__RT_,
	otawa_kind_LDRB_RD___LT_RD___ID_RT_,
	otawa_kind_LDR_RD___LT_SP___ID__2A_4_RT_,
	otawa_kind_LDR_RD___LT_PC___ID__2A_4_RT_,
	otawa_kind_LDR_RD___LT_RD__RD__RT_,
	otawa_kind_LDR_RD___LT_RD___ID__2A_4_RT_,
	otawa_kind_LDMIA_RD_21___LB_S_RB_,
	otawa_kind_EOR_RD__RD,
	otawa_kind_CMP_RD__S,
	otawa_kind_CMP_RD__RD,
	otawa_kind_CMP_RD___ID,
	otawa_kind_CMN_RD__RD,
	otawa_kind_BX_S,
	otawa_kind_BLX_S,
	otawa_kind_BLS_D,
	otawa_kind_BIC_RD__RD,
	otawa_kind_S__ID,
	otawa_kind_ASR_RD__RD,
	otawa_kind_ASR_RD__RD___ID,
	otawa_kind_AND_RD__RD,
	otawa_kind_ADD_RD__S,
	otawa_kind_ADD_RD__RD__RD,
	otawa_kind_ADD_SP___ID,
	otawa_kind_ADD_RD___ID,
	otawa_kind_ADD_RD___ID_0,
	otawa_kind_ADD_RD___ID_1,
	otawa_kind_ADD_RD__RD___ID,
	otawa_kind_ADC_RD__RD,
	otawa_kind_MRSS_S__CPSR,
	otawa_kind_MRSS_S__SPSR,
	otawa_kind_MSRS_CPSR___S,
	otawa_kind_MSRS_CPSR_FSXC__S,
	otawa_kind_MSRS_CPSR_SXC__S,
	otawa_kind_MSRS_CPSR_FXC__S,
	otawa_kind_MSRS_CPSR_FSX__S,
	otawa_kind_MSRS_CPSR_XC__S,
	otawa_kind_MSRS_CPSR_SC__S,
	otawa_kind_MSRS_CPSR_SX__S,
	otawa_kind_MSRS_CPSR_F__S,
	otawa_kind_MSRS_CPSR_FX__S,
	otawa_kind_MSRS_CPSR_FS__S,
	otawa_kind_MSRS_CPSR_C__S,
	otawa_kind_MSRS_CPSR_X__S,
	otawa_kind_MSRS_CPSR_S__S,
	otawa_kind_MSRS_CPSR_F__S_0,
	otawa_kind_MSRS_SPSR___S,
	otawa_kind_MSRS_SPSR_FSXC__S,
	otawa_kind_MSRS_SPSR_SXC__S,
	otawa_kind_MSRS_SPSR_FXC__S,
	otawa_kind_MSRS_SPSR_FSX__S,
	otawa_kind_MSRS_SPSR_XC__S,
	otawa_kind_MSRS_SPSR_SC__S,
	otawa_kind_MSRS_SPSR_SX__S,
	otawa_kind_MSRS_SPSR_F__S,
	otawa_kind_MSRS_SPSR_FX__S,
	otawa_kind_MSRS_SPSR_FS__S,
	otawa_kind_MSRS_SPSR_C__S,
	otawa_kind_MSRS_SPSR_X__S,
	otawa_kind_MSRS_SPSR_S__S,
	otawa_kind_MSRS_SPSR_F__S_0,
	otawa_kind_MSRS_CPSR____ID,
	otawa_kind_MSRS_CPSR_FSXC___ID,
	otawa_kind_MSRS_CPSR_SXC___ID,
	otawa_kind_MSRS_CPSR_FXC___ID,
	otawa_kind_MSRS_CPSR_FSX___ID,
	otawa_kind_MSRS_CPSR_XC___ID,
	otawa_kind_MSRS_CPSR_SC___ID,
	otawa_kind_MSRS_CPSR_SX___ID,
	otawa_kind_MSRS_CPSR_F___ID,
	otawa_kind_MSRS_CPSR_FX___ID,
	otawa_kind_MSRS_CPSR_FS___ID,
	otawa_kind_MSRS_CPSR_C___ID,
	otawa_kind_MSRS_CPSR_X___ID,
	otawa_kind_MSRS_CPSR_S___ID,
	otawa_kind_MSRS_CPSR_F___ID_0,
	otawa_kind_MSRS_SPSR____ID,
	otawa_kind_MSRS_SPSR_FSXC___ID,
	otawa_kind_MSRS_SPSR_SXC___ID,
	otawa_kind_MSRS_SPSR_FXC___ID,
	otawa_kind_MSRS_SPSR_FSX___ID,
	otawa_kind_MSRS_SPSR_XC___ID,
	otawa_kind_MSRS_SPSR_SC___ID,
	otawa_kind_MSRS_SPSR_SX___ID,
	otawa_kind_MSRS_SPSR_F___ID,
	otawa_kind_MSRS_SPSR_FX___ID,
	otawa_kind_MSRS_SPSR_FS___ID,
	otawa_kind_MSRS_SPSR_C___ID,
	otawa_kind_MSRS_SPSR_X___ID,
	otawa_kind_MSRS_SPSR_S___ID,
	otawa_kind_MSRS_SPSR_F___ID_0,
	otawa_kind_CLZS_S__S,
	otawa_kind_SWPS_S__S___LT_S_RT_,
	otawa_kind_SWPSB_S__S___LT_S_RT_,
	otawa_kind_UMLALSS_S_S_S_S,
	otawa_kind_SMLALSS_S_S_S_S,
	otawa_kind_UMULLSS_S_S_S_S,
	otawa_kind_SMULLSS_S_S_S_S,
	otawa_kind_MULSS_S__S__S,
	otawa_kind_MLASS_S__S__S__S,
	otawa_kind_SWIS_D,
	otawa_kind_SMSS_SS___LB_S_RB_S,
	otawa_kind_LDRSSH_S___LT_SS_SSSS,
	otawa_kind_LDRSSH_S___LT_SS_S_IDSS,
	otawa_kind_LDRSSB_S___LT_SS_SSSS,
	otawa_kind_LDRSSB_S___LT_SS_S_IDSS,
	otawa_kind_LDRSH_S___LT_SS_SSSS,
	otawa_kind_LDRSH_S___LT_SS_S_IDSS,
	otawa_kind_STRSH_S___LT_SS_SSSS,
	otawa_kind_STRSH_S___LT_SS_S_IDSS,
	otawa_kind_SRSSS_S___LT_SS__SS__S__IDSS,
	otawa_kind_SRSSS_S___LT_SS_S_IDSS,
	otawa_kind_BSS_X,
	otawa_kind_BXS_S,
	otawa_kind_TSTS_S___ID,
	otawa_kind_TSTS_S__S__S_S,
	otawa_kind_TSTS_S__S__S__ID,
	otawa_kind_TEQS_S___ID,
	otawa_kind_TEQS_S__S__S_S,
	otawa_kind_TEQS_S__S__S__ID,
	otawa_kind_SUBSS_S__S___ID,
	otawa_kind_SUBSS_S__S__S__S_S,
	otawa_kind_SUBSS_S__S__S__S__ID,
	otawa_kind_SBCSS_S__S___ID,
	otawa_kind_SBCSS_S__S__S__S_S,
	otawa_kind_SBCSS_S__S__S__S__ID,
	otawa_kind_RSCSS_S__S___ID,
	otawa_kind_RSCSS_S__S__S__S_S,
	otawa_kind_RSCSS_S__S__S__S__ID,
	otawa_kind_RSBSS_S__S___ID,
	otawa_kind_RSBSS_S__S__S__S_S,
	otawa_kind_RSBSS_S__S__S__S__ID,
	otawa_kind_ORRSS_S__S___ID,
	otawa_kind_ORRSS_S__S__S__S_S,
	otawa_kind_ORRSS_S__S__S__S__ID,
	otawa_kind_MVNSS_S___ID,
	otawa_kind_MVNSS_S__S__S_S,
	otawa_kind_MVNSS_S__S__S__ID,
	otawa_kind_MOVSS_S___ID,
	otawa_kind_MOVSS_S__S__S_S,
	otawa_kind_MOVSS_S__S__S__ID,
	otawa_kind_EORSS_S__S___ID,
	otawa_kind_EORSS_S__S__S__S_S,
	otawa_kind_EORSS_S__S__S__S__ID,
	otawa_kind_CMPS_S___ID,
	otawa_kind_CMPS_S__S__S_S,
	otawa_kind_CMPS_S__S__S__ID,
	otawa_kind_CMNS_S___ID,
	otawa_kind_CMNS_S__S__S_S,
	otawa_kind_CMNS_S__S__S__ID,
	otawa_kind_BICSS_S__S___ID,
	otawa_kind_BICSS_S__S__S__S_S,
	otawa_kind_BICSS_S__S__S__S__ID,
	otawa_kind_ANDSS_S__S___ID,
	otawa_kind_ANDSS_S__S__S__S_S,
	otawa_kind_ANDSS_S__S__S__S__ID,
	otawa_kind_ADDSS_S__S__S__S_S,
	otawa_kind_ADDSS_S__S__S__S__ID,
	otawa_kind_ADCSS_S__S___ID,
	otawa_kind_ADCSS_S__S__S__S_S,
	otawa_kind_ADCSS_S__S__S__S__ID,
	otawa_kind_ADDSS_S__S___ID
};

/**
 * Get the OTAWA kind of the instruction.
 * @return OTAWA kind.
 */
otawa_kind_t arm_kind(arm_inst_t *inst) {
	return kind_funs[inst->ident](inst);
}

#ifdef __cplusplus
}
#endif
