/* Generated by gliss-attr ($(date)) copyright (c) 2009 IRIT - UPS */

extern "C" {
#include <$(proc)/api.h>
#include <$(proc)/id.h>
#include <$(proc)/macros.h>
#include <$(proc)/grt.h>
}

typedef void (*ksem_fun_t)($(proc)_inst_t *inst, otawa::sem::Block& block);

/*** functions ***/

static void otawa_ksem_UNKNOWN($(proc)_inst_t *inst, otawa::sem::Block& block) {
}

$(foreach instructions)
static void otawa_ksem_$(IDENT)($(proc)_inst_t *inst, otawa::sem::Block& block) {
$(otawa_ksem!)
};

$(end)


/*** function table ***/
static ksem_fun_t ksem_funs[] = {
	otawa_ksem_UNKNOWN$(foreach instructions),
	otawa_ksem_$(IDENT)$(end)
};

/**
 * Get the OTAWA semantics kernel of the instruction.
 * @param inst		Current GLISS instruction.
 * @param block		Block to write semantic instructions in.
 */
static void $(proc)_ksem($(proc)_inst_t *inst, otawa::sem::Block& block) {
	ksem_funs[inst->ident](inst, block);
}
