/* Generated by gliss-attr ($(date)) copyright (c) 2009 IRIT - UPS */

#include <$(proc)/api.h>
#include <$(proc)/id.h>
#include <$(proc)/macros.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef int (*multi_fun_t)($(proc)_inst_t *inst);



static int otawa_multi_UNKNOWN($(proc)_inst_t *inst) {
        return 0;
}

$(foreach instructions)
static int otawa_multi_$(IDENT)($(proc)_inst_t *inst) {
$(otawa_multi)
};

$(end)


/* function table */
static multi_fun_t $(proc)_multi_table[] = {
	otawa_multi_UNKNOWN$(foreach instructions),
	otawa_multi_$(IDENT)$(end)
};



/**
 * Get the multiple-register count of the instruction.
 * @return multiple-register count.
 */
int $(proc)_multi($(proc)_inst_t *inst) {
        return $(proc)_multi_table[inst->ident](inst);
}

#ifdef __cplusplus
}
#endif

