/* Generated by gliss-attr (112/05/12 16:28:50) copyright (c) 2009 IRIT - UPS */

#include <arm/api.h>
#include <arm/id.h>
#include <arm/macros.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef uint32_t otawa_target_t;

typedef otawa_target_t (*target_fun_t)(arm_inst_t *inst);



static otawa_target_t otawa_target_UNKNOWN(arm_inst_t *inst)
{
        /* this code should also be used as default value if
        an instruction has no otawa_target field */
        return 0;
}

static otawa_target_t otawa_target_MOV_RD__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MOV_RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TST_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUB_RD__RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUB_SP___ID__2A_4(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUB_RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUB_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRH_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRH_RD___LT_RD___ID__2A_2_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRB_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRB_RD___LT_RD___ID_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STR_RD___LT_SP___ID__2A_4_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STR_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STR_RD___LT_RD___ID__2A_4_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STMIA_RD_21___LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SBC_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ROR_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_PUSH__LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_PUSH__LB_S_RB__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_POP__LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_POP__LB_S_RB__0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORR_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_NEG_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MVN_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MUL_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LSR_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LSR_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LSL_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LSL_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSH_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSB_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRH_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRH_RD___LT_RD___ID__2A_2_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRB_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRB_RD___LT_RD___ID_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDR_RD___LT_SP___ID__2A_4_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDR_RD___LT_PC___ID__2A_4_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDR_RD___LT_RD__RD__RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDR_RD___LT_RD___ID__2A_4_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDMIA_RD_21___LB_S_RB_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EOR_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMP_RD__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMP_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMP_RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMN_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BX_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BLX_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BLS_D(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BIC_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_S__ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ASR_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ASR_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_AND_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADD_RD__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADD_RD__RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADD_SP___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADD_RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADD_RD___ID_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADD_RD___ID_1(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADD_RD__RD___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADC_RD__RD(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MRSS_S__CPSR(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MRSS_S__SPSR(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR___S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FSXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_SXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FSX__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_XC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_SC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_SX__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_F__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FX__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FS__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_C__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_X__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_F__S_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR___S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FSXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_SXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FXC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FSX__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_XC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_SC__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_SX__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_F__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FX__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FS__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_C__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_X__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_F__S_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR____ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FSXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_SXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FSX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_XC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_SC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_SX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_F___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_FS___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_C___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_X___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_CPSR_F___ID_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR____ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FSXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_SXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FXC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FSX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_XC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_SC___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_SX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_F___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FX___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_FS___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_C___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_X___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MSRS_SPSR_F___ID_0(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CDPS_D__D__D__D__D__D(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BFIS_S___ID___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CLZS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SWPS_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SWPSB_S__S___LT_S_RT_(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UMLALSS_S_S_S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SMLALSS_S_S_S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_UMULLSS_S_S_S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SMULLSS_S_S_S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MULSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MLASS_S__S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SWIS_D(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDMSS_SS___LB_S_RB_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STMSS_SS___LB_S_RB_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSSH_S___LT_SS_SSSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSSH_S___LT_SS_S_ILUSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSSB_S___LT_SS_SSSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSSB_S___LT_SS_S_ILUSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSH_S___LT_SS_SSSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSH_S___LT_SS_S_ILUSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRSH_S___LT_SS_SSSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRSH_S___LT_SS_S_ILUSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRSSS_S___LT_SS__SS__S__IDSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSSS_S___LT_SS__SS__S__IDSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_STRSSS_S___LT_SS_S_IDSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_LDRSSS_S___LT_SS_S_IDSS(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BSS_X(arm_inst_t *inst) {
	return ((ARM_BSS_X___IADDR + 8) + arm_concat32(ARM_BSS_X_x_signed_immed_24_n, 0, 30, 2));

};

static otawa_target_t otawa_target_BXS_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TSTS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TSTS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TSTS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TEQS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TEQS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_TEQS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SUBSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SBCSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SBCSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_SBCSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RSCSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RSCSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RSCSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RSBSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RSBSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_RSBSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORRSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORRSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ORRSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MVNSS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MVNSS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MVNSS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MOVSS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MOVSS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_MOVSS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EORSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EORSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_EORSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMPS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMPS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMPS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMNS_S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMNS_S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_CMNS_S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BICSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BICSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_BICSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ANDSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ANDSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ANDSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADCSS_S__S___ID(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADCSS_S__S__S__S_S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADCSS_S__S__S(arm_inst_t *inst) {
return 0;
};

static otawa_target_t otawa_target_ADDSS_S__S___ID(arm_inst_t *inst) {
return 0;
};




/* function table */
static target_fun_t arm_target_table[] =
{
	otawa_target_UNKNOWN,
	otawa_target_MOV_RD__S,
	otawa_target_MOV_RD___ID,
	otawa_target_TST_RD__RD,
	otawa_target_SUB_RD__RD__RD,
	otawa_target_SUB_SP___ID__2A_4,
	otawa_target_SUB_RD___ID,
	otawa_target_SUB_RD__RD___ID,
	otawa_target_STRH_RD___LT_RD__RD__RT_,
	otawa_target_STRH_RD___LT_RD___ID__2A_2_RT_,
	otawa_target_STRB_RD___LT_RD__RD__RT_,
	otawa_target_STRB_RD___LT_RD___ID_RT_,
	otawa_target_STR_RD___LT_SP___ID__2A_4_RT_,
	otawa_target_STR_RD___LT_RD__RD__RT_,
	otawa_target_STR_RD___LT_RD___ID__2A_4_RT_,
	otawa_target_STMIA_RD_21___LB_S_RB_,
	otawa_target_SBC_RD__RD,
	otawa_target_ROR_RD__RD,
	otawa_target_PUSH__LB_S_RB_,
	otawa_target_PUSH__LB_S_RB__0,
	otawa_target_POP__LB_S_RB_,
	otawa_target_POP__LB_S_RB__0,
	otawa_target_ORR_RD__RD,
	otawa_target_NEG_RD__RD,
	otawa_target_MVN_RD__RD,
	otawa_target_MUL_RD__RD,
	otawa_target_LSR_RD__RD,
	otawa_target_LSR_RD__RD___ID,
	otawa_target_LSL_RD__RD,
	otawa_target_LSL_RD__RD___ID,
	otawa_target_LDRSH_RD___LT_RD__RD__RT_,
	otawa_target_LDRSB_RD___LT_RD__RD__RT_,
	otawa_target_LDRH_RD___LT_RD__RD__RT_,
	otawa_target_LDRH_RD___LT_RD___ID__2A_2_RT_,
	otawa_target_LDRB_RD___LT_RD__RD__RT_,
	otawa_target_LDRB_RD___LT_RD___ID_RT_,
	otawa_target_LDR_RD___LT_SP___ID__2A_4_RT_,
	otawa_target_LDR_RD___LT_PC___ID__2A_4_RT_,
	otawa_target_LDR_RD___LT_RD__RD__RT_,
	otawa_target_LDR_RD___LT_RD___ID__2A_4_RT_,
	otawa_target_LDMIA_RD_21___LB_S_RB_,
	otawa_target_EOR_RD__RD,
	otawa_target_CMP_RD__S,
	otawa_target_CMP_RD__RD,
	otawa_target_CMP_RD___ID,
	otawa_target_CMN_RD__RD,
	otawa_target_BX_S,
	otawa_target_BLX_S,
	otawa_target_BLS_D,
	otawa_target_BIC_RD__RD,
	otawa_target_S__ID,
	otawa_target_ASR_RD__RD,
	otawa_target_ASR_RD__RD___ID,
	otawa_target_AND_RD__RD,
	otawa_target_ADD_RD__S,
	otawa_target_ADD_RD__RD__RD,
	otawa_target_ADD_SP___ID,
	otawa_target_ADD_RD___ID,
	otawa_target_ADD_RD___ID_0,
	otawa_target_ADD_RD___ID_1,
	otawa_target_ADD_RD__RD___ID,
	otawa_target_ADC_RD__RD,
	otawa_target_MRSS_S__CPSR,
	otawa_target_MRSS_S__SPSR,
	otawa_target_MSRS_CPSR___S,
	otawa_target_MSRS_CPSR_FSXC__S,
	otawa_target_MSRS_CPSR_SXC__S,
	otawa_target_MSRS_CPSR_FXC__S,
	otawa_target_MSRS_CPSR_FSX__S,
	otawa_target_MSRS_CPSR_XC__S,
	otawa_target_MSRS_CPSR_SC__S,
	otawa_target_MSRS_CPSR_SX__S,
	otawa_target_MSRS_CPSR_F__S,
	otawa_target_MSRS_CPSR_FX__S,
	otawa_target_MSRS_CPSR_FS__S,
	otawa_target_MSRS_CPSR_C__S,
	otawa_target_MSRS_CPSR_X__S,
	otawa_target_MSRS_CPSR_S__S,
	otawa_target_MSRS_CPSR_F__S_0,
	otawa_target_MSRS_SPSR___S,
	otawa_target_MSRS_SPSR_FSXC__S,
	otawa_target_MSRS_SPSR_SXC__S,
	otawa_target_MSRS_SPSR_FXC__S,
	otawa_target_MSRS_SPSR_FSX__S,
	otawa_target_MSRS_SPSR_XC__S,
	otawa_target_MSRS_SPSR_SC__S,
	otawa_target_MSRS_SPSR_SX__S,
	otawa_target_MSRS_SPSR_F__S,
	otawa_target_MSRS_SPSR_FX__S,
	otawa_target_MSRS_SPSR_FS__S,
	otawa_target_MSRS_SPSR_C__S,
	otawa_target_MSRS_SPSR_X__S,
	otawa_target_MSRS_SPSR_S__S,
	otawa_target_MSRS_SPSR_F__S_0,
	otawa_target_MSRS_CPSR____ID,
	otawa_target_MSRS_CPSR_FSXC___ID,
	otawa_target_MSRS_CPSR_SXC___ID,
	otawa_target_MSRS_CPSR_FXC___ID,
	otawa_target_MSRS_CPSR_FSX___ID,
	otawa_target_MSRS_CPSR_XC___ID,
	otawa_target_MSRS_CPSR_SC___ID,
	otawa_target_MSRS_CPSR_SX___ID,
	otawa_target_MSRS_CPSR_F___ID,
	otawa_target_MSRS_CPSR_FX___ID,
	otawa_target_MSRS_CPSR_FS___ID,
	otawa_target_MSRS_CPSR_C___ID,
	otawa_target_MSRS_CPSR_X___ID,
	otawa_target_MSRS_CPSR_S___ID,
	otawa_target_MSRS_CPSR_F___ID_0,
	otawa_target_MSRS_SPSR____ID,
	otawa_target_MSRS_SPSR_FSXC___ID,
	otawa_target_MSRS_SPSR_SXC___ID,
	otawa_target_MSRS_SPSR_FXC___ID,
	otawa_target_MSRS_SPSR_FSX___ID,
	otawa_target_MSRS_SPSR_XC___ID,
	otawa_target_MSRS_SPSR_SC___ID,
	otawa_target_MSRS_SPSR_SX___ID,
	otawa_target_MSRS_SPSR_F___ID,
	otawa_target_MSRS_SPSR_FX___ID,
	otawa_target_MSRS_SPSR_FS___ID,
	otawa_target_MSRS_SPSR_C___ID,
	otawa_target_MSRS_SPSR_X___ID,
	otawa_target_MSRS_SPSR_S___ID,
	otawa_target_MSRS_SPSR_F___ID_0,
	otawa_target_CDPS_D__D__D__D__D__D,
	otawa_target_BFIS_S___ID___ID,
	otawa_target_CLZS_S__S,
	otawa_target_SWPS_S__S___LT_S_RT_,
	otawa_target_SWPSB_S__S___LT_S_RT_,
	otawa_target_UMLALSS_S_S_S_S,
	otawa_target_SMLALSS_S_S_S_S,
	otawa_target_UMULLSS_S_S_S_S,
	otawa_target_SMULLSS_S_S_S_S,
	otawa_target_MULSS_S__S__S,
	otawa_target_MLASS_S__S__S__S,
	otawa_target_SWIS_D,
	otawa_target_LDMSS_SS___LB_S_RB_S,
	otawa_target_STMSS_SS___LB_S_RB_S,
	otawa_target_LDRSSH_S___LT_SS_SSSS,
	otawa_target_LDRSSH_S___LT_SS_S_ILUSS,
	otawa_target_LDRSSB_S___LT_SS_SSSS,
	otawa_target_LDRSSB_S___LT_SS_S_ILUSS,
	otawa_target_LDRSH_S___LT_SS_SSSS,
	otawa_target_LDRSH_S___LT_SS_S_ILUSS,
	otawa_target_STRSH_S___LT_SS_SSSS,
	otawa_target_STRSH_S___LT_SS_S_ILUSS,
	otawa_target_STRSSS_S___LT_SS__SS__S__IDSS,
	otawa_target_LDRSSS_S___LT_SS__SS__S__IDSS,
	otawa_target_STRSSS_S___LT_SS_S_IDSS,
	otawa_target_LDRSSS_S___LT_SS_S_IDSS,
	otawa_target_BSS_X,
	otawa_target_BXS_S,
	otawa_target_TSTS_S___ID,
	otawa_target_TSTS_S__S__S_S,
	otawa_target_TSTS_S__S,
	otawa_target_TEQS_S___ID,
	otawa_target_TEQS_S__S__S_S,
	otawa_target_TEQS_S__S,
	otawa_target_SUBSS_S__S___ID,
	otawa_target_SUBSS_S__S__S__S_S,
	otawa_target_SUBSS_S__S__S,
	otawa_target_SBCSS_S__S___ID,
	otawa_target_SBCSS_S__S__S__S_S,
	otawa_target_SBCSS_S__S__S,
	otawa_target_RSCSS_S__S___ID,
	otawa_target_RSCSS_S__S__S__S_S,
	otawa_target_RSCSS_S__S__S,
	otawa_target_RSBSS_S__S___ID,
	otawa_target_RSBSS_S__S__S__S_S,
	otawa_target_RSBSS_S__S__S,
	otawa_target_ORRSS_S__S___ID,
	otawa_target_ORRSS_S__S__S__S_S,
	otawa_target_ORRSS_S__S__S,
	otawa_target_MVNSS_S___ID,
	otawa_target_MVNSS_S__S__S_S,
	otawa_target_MVNSS_S__S,
	otawa_target_MOVSS_S___ID,
	otawa_target_MOVSS_S__S__S_S,
	otawa_target_MOVSS_S__S,
	otawa_target_EORSS_S__S___ID,
	otawa_target_EORSS_S__S__S__S_S,
	otawa_target_EORSS_S__S__S,
	otawa_target_CMPS_S___ID,
	otawa_target_CMPS_S__S__S_S,
	otawa_target_CMPS_S__S,
	otawa_target_CMNS_S___ID,
	otawa_target_CMNS_S__S__S_S,
	otawa_target_CMNS_S__S,
	otawa_target_BICSS_S__S___ID,
	otawa_target_BICSS_S__S__S__S_S,
	otawa_target_BICSS_S__S__S,
	otawa_target_ANDSS_S__S___ID,
	otawa_target_ANDSS_S__S__S__S_S,
	otawa_target_ANDSS_S__S__S,
	otawa_target_ADDSS_S__S__S__S_S,
	otawa_target_ADDSS_S__S__S,
	otawa_target_ADCSS_S__S___ID,
	otawa_target_ADCSS_S__S__S__S_S,
	otawa_target_ADCSS_S__S__S,
	otawa_target_ADDSS_S__S___ID
};



/**
 * Get the OTAWA target of the instruction.
 * @return OTAWA target.
 */
otawa_target_t arm_target(arm_inst_t *inst)
{
        return arm_target_table[inst->ident](inst);
}

#ifdef __cplusplus
}
#endif

